name: Bug Report
description: Create a bug report to help me find and fix bugs!
title: "[Bug]"
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what you're experiencing. If applicable, add screenshots to help explain your problem.
  validations:
    required: true
- type: input
  attributes:
    label: Plugin Version
    description: What version of the plugin are you running?
    placeholder: "e.g. v1.2.3"
  validations:
    required: true

- type: input
  attributes:
    label: Millennium Version
    description: What version of Millennium are you using?
    placeholder: "e.g. v2.17.2"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating System
    options:
      - Windows
      - Linux
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear and concise description of what actually happened.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Reproducibility
    description: Is this issue consistently reproducible?
    options:
      - label: Yes, I can reproduce this issue consistently
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With these settings...
      3. Click '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshots? Anything that will give me more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
