name: Feature Request
description: Suggest an idea for this plugin!
title: "[Feature]"
labels: [enhancement]
body:
- type: textarea
  attributes:
    label: Describe the feature you'd like!
    description: A clear and concise description of what you want to see to be added to this plugin.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshots? Anything that will give me more context about the feature you are requesting!

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
